### ISSUE TITLE
Q.: Datasets that are not publicly available anymore

### ISSUE THREAD

**Issue by ocramz** [filopodia/open#1]
Would you consider a PR for datasets that do not have a working download link anymore but that some users might still own?

I'm thinking for example of the Netflix prize data.

**Comment by glutamate** [comment]
Yes, i think this is fine. Just make this clear in the module docs.

**Comment by ocramz** [comment]
Good to hear! Also, I would need to add `attoparsec` as a dependency , is it fine with you? I think it would also benefit other datasets in the future

**Comment by glutamate** [comment]
Yes that is fine. It is probably implied by cassava or aeson anyways

**Comment by ocramz** [comment]
PR sent!
